github.com:
    users:
        praxshannu:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: praxshannu
